//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleMultiLang.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleMultiLang.Resource.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curtain.
        /// </summary>
        internal static string Curtain {
            get {
                return ResourceManager.GetString("Curtain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown notification.
        /// </summary>
        internal static string NotificationCode_0 {
            get {
                return ResourceManager.GetString("NotificationCode_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was switched On.
        /// </summary>
        internal static string NotificationCode_1 {
            get {
                return ResourceManager.GetString("NotificationCode_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Attempt:Force Lock.
        /// </summary>
        internal static string NotificationCode_10 {
            get {
                return ResourceManager.GetString("NotificationCode_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Set.
        /// </summary>
        internal static string NotificationCode_11 {
            get {
                return ResourceManager.GetString("NotificationCode_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Triggered.
        /// </summary>
        internal static string NotificationCode_12 {
            get {
                return ResourceManager.GetString("NotificationCode_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panic button caused alarm to trigger.
        /// </summary>
        internal static string NotificationCode_13 {
            get {
                return ResourceManager.GetString("NotificationCode_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Triggered by Zone.
        /// </summary>
        internal static string NotificationCode_14 {
            get {
                return ResourceManager.GetString("NotificationCode_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed.
        /// </summary>
        internal static string NotificationCode_15 {
            get {
                return ResourceManager.GetString("NotificationCode_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disarmed.
        /// </summary>
        internal static string NotificationCode_16 {
            get {
                return ResourceManager.GetString("NotificationCode_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition Armed.
        /// </summary>
        internal static string NotificationCode_17 {
            get {
                return ResourceManager.GetString("NotificationCode_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string NotificationCode_18 {
            get {
                return ResourceManager.GetString("NotificationCode_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WATrigger.
        /// </summary>
        internal static string NotificationCode_19 {
            get {
                return ResourceManager.GetString("NotificationCode_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was switched Off.
        /// </summary>
        internal static string NotificationCode_2 {
            get {
                return ResourceManager.GetString("NotificationCode_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was On.
        /// </summary>
        internal static string NotificationCode_3 {
            get {
                return ResourceManager.GetString("NotificationCode_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was Off.
        /// </summary>
        internal static string NotificationCode_4 {
            get {
                return ResourceManager.GetString("NotificationCode_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string NotificationCode_5 {
            get {
                return ResourceManager.GetString("NotificationCode_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Added.
        /// </summary>
        internal static string NotificationCode_6 {
            get {
                return ResourceManager.GetString("NotificationCode_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Removed.
        /// </summary>
        internal static string NotificationCode_7 {
            get {
                return ResourceManager.GetString("NotificationCode_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Battery.
        /// </summary>
        internal static string NotificationCode_8 {
            get {
                return ResourceManager.GetString("NotificationCode_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wake Up.
        /// </summary>
        internal static string NotificationCode_9 {
            get {
                return ResourceManager.GetString("NotificationCode_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        internal static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
    }
}
